# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neues Event', max_length=200)),
                ('beschreibung', models.TextField(default='Keine Beschreibung vorhanden.')),
                ('bild', models.ImageField(default='images/no-img.png', upload_to='images/events/')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('beginn', models.DateTimeField(default=datetime.datetime.now)),
                ('ende', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='kategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Kategorie'),
        ),
    ]
