# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='titel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='beginn',
        ),
        migrations.RemoveField(
            model_name='event',
            name='beschreibung',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ende',
        ),
        migrations.RemoveField(
            model_name='event',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='event',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Location', max_length=200),
        ),
    ]
