# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161206_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='titel',
            field=models.CharField(default='Neues Event', max_length=100),
        ),
    ]
