# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161111_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
