# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datum',
        ),
        migrations.AddField(
            model_name='event',
            name='beginn',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 16, 31, 53, 498021)),
        ),
        migrations.AddField(
            model_name='event',
            name='beschreibung',
            field=models.CharField(default='Beschreibung', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='ende',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 16, 31, 53, 498055)),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
    ]
