# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161111_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
