# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beschreibung',
            field=models.TextField(default='Keine Beschreibung vorhanden.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/'),
        ),
    ]
