# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161211_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mindestalter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='beginn',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 17, 27, 37, 185219)),
        ),
        migrations.AlterField(
            model_name='event',
            name='ende',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 17, 27, 37, 185257)),
        ),
    ]
